image: node:10


build:
  only:
    - develop
  artifacts:
    paths:
      - public
  script:
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_KEY" | tr --delete '\r' | ssh-add - > /dev/null
    - mkdir --parents ~/.ssh
    - chmod 700 ~/.ssh
    - echo 'github.com,192.30.253.113 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' > ~/.ssh/known_hosts
    - git config --global user.email "kontakt@javascript-in-jena.de"
    - git config --global user.name "Gitlab Build System"
    - git clone git@github.com:javascript-in-jena/javascript-in-jena.github.io.git public
    - npm ci
    - cd public
    - rm --recursive *
    - npm run build:sass
    - npm run build
    - git add *
    - git commit  -m "$(echo -e "Build $CI_COMMIT_SHA\nAuthor $GITLAB_USER_NAME\nAenderungen\n\n$CI_COMMIT_MESSAGE")"
    - git push