baseURL = "https://jena.js.org"
title = "JavaScript in Jena"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "de"

[params.info]
description = "Treffen von JavaScript Entwicklern in und um Jena"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

# [params.copyright]
# prefix = ""
# holder = "JavaScript in Jena"
# startYear = "2018"
# suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
archiveDateFormat = "2006-01-02"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
# homepage = ["recent_posts"]
sidebar = ["about","sidebar_menu", "social_menu"]
# footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
#codepen = "MunifTanjim"
email = "kontakt@javascript-in-jena.de"
# facebook = "MunifTanjim"
github = "javascript-in-jena"
gitlab = "javascript-in-jena"
#instagram = "MunifTanjim"
#linkedin = "muniftanjim"
#twitter = "MunifTanjim"
#telegram = "MunifTanjim"
#google_scholar = "qc6CJjYAAAAJ"
#youtube = "UCT-U0rNerYxItGcuoPX-WYA"

[params.comments]
enable = false

[params.comments.staticman]
enable = true
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2

[params.comments.staticman.github]
username = "MunifTanjim"
repository = "minimo"
branch = "master"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title

[params.comments.utterances.github]
username = "MunifTanjim"
repository = "minimo"

[params.search]
client = "" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
# author = "authors"
category = "categories"
# series = "series"
# tag = "tags"

[permalinks]
page = "/:slug/"

# [[menu.main]]
# name = "Nächstes Treffen"
# weight = -10
# identifier = "naechstes-treffen"
# url = "/treffen/2018-08-16/"

# [[menu.sidebar]]
# name = "Nächstes Treffen"
# weight = -10
# identifier = "treffen/2018-08-16/"
# url = "/treffen/2018-08-16/"

[blackfriday]
hrefTargetBlank = false

[languages]
# edit this block for your own language
[languages.de]
lang = "de"
languageName = "Deutsch"
weight = 1
